### ISSUE TITLE
Error when running yarn build – Invalid "path" argument in fuselage-tokens package

### ISSUE THREAD

**Issue by dhruuvarora** [RocketChat/fuselage#1489]
I'm encountering an error while running yarn build in the root directory of the project. The build process fails at the @rocket.chat/fuselage-tokens package, throwing the following error:

dhruv@dhruv-Inspiron-13-5320:~/fuselage$ yarn build
╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.2.3 ≫ v2.3.3                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.3    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
turbo 2.2.3

• Packages in scope: @rocket.chat/css-in-js, @rocket.chat/css-supports, @rocket.chat/emitter, @rocket.chat/fuselage, @rocket.chat/fuselage-hooks, @rocket.chat/fuselage-polyfills, @rocket.chat/fuselage-toastbar, @rocket.chat/fuselage-tokens, @rocket.chat/icons, @rocket.chat/layout, @rocket.chat/logo, @rocket.chat/memo, @rocket.chat/mp3-encoder, @rocket.chat/onboarding-ui, @rocket.chat/peggy-loader, @rocket.chat/prettier-config, @rocket.chat/string-helpers, @rocket.chat/styled, @rocket.chat/stylis-logical-props-middleware, build-design-tokens, build-icons, build-logo, lint-all, scripts, testing-utils, tools-utils, update-readme
• Running build in 27 packages
• Remote caching disabled
@rocket.chat/string-helpers:build: cache hit, replaying logs 75638d3078ac7558
@rocket.chat/memo:build: cache hit, replaying logs 6ec34bf3b9eb767e
@rocket.chat/emitter:build: cache hit, replaying logs 42c4cee43ee8e477
@rocket.chat/emitter:build: 
@rocket.chat/emitter:build: src/index.ts → dist, dist, dist...
@rocket.chat/emitter:build: created dist, dist, dist in 3.4s
@rocket.chat/peggy-loader:build: cache hit, replaying logs 4002d40fb4495df7
@rocket.chat/mp3-encoder:build: cache miss, executing 79265fffc487cb80
@rocket.chat/mp3-encoder:build: 
@rocket.chat/fuselage-tokens:build: cache miss, executing 35b725ca761a2ad1
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/css-supports:build: cache hit, replaying logs 7ece230323075392
@rocket.chat/css-supports:build: 
@rocket.chat/icons:build: cache hit, replaying logs c3917562e1b0e75c
@rocket.chat/icons:build: 
@rocket.chat/icons:build: 
@rocket.chat/stylis-logical-props-middleware:build: cache hit, replaying logs aaffd24cea965b2d
@rocket.chat/stylis-logical-props-middleware:build: 
@rocket.chat/css-in-js:build: cache hit, replaying logs 3bff37403f0eaf47
@rocket.chat/css-in-js:build: 
@rocket.chat/css-in-js:build: 
@rocket.chat/css-in-js:build: src/index.ts → dist, dist, dist...
@rocket.chat/css-in-js:build: created dist, dist, dist in 2s
@rocket.chat/styled:build: cache miss, executing c6908888bd8f6ba5
@rocket.chat/styled:build: 
@rocket.chat/mp3-encoder:build: 
@rocket.chat/mp3-encoder:build: src/index.ts → dist...
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/mp3-encoder:build: created dist in 2.9s
@rocket.chat/mp3-encoder:build: 
@rocket.chat/mp3-encoder:build: src/index.ts → dist/index.mjs...
@rocket.chat/fuselage-tokens:build: Build started...
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: ==============================================
@rocket.chat/fuselage-tokens:build: node:internal/errors:496
@rocket.chat/fuselage-tokens:build:     ErrorCaptureStackTrace(err);
@rocket.chat/fuselage-tokens:build:     ^
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
@rocket.chat/fuselage-tokens:build:     at readdirSync (node:fs:1512:10)
@rocket.chat/fuselage-tokens:build:     at dirs (file:///home/dhruv/fuselage/packages/fuselage-tokens/src/index.js:5:3)
@rocket.chat/fuselage-tokens:build:     at file:///home/dhruv/fuselage/packages/fuselage-tokens/src/index.js:7:16
@rocket.chat/fuselage-tokens:build:     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
@rocket.chat/fuselage-tokens:build:     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
@rocket.chat/fuselage-tokens:build:     at async StyleDictionary.extend (file:///home/dhruv/fuselage/packages/fuselage-tokens/node_modules/style-dictionary/lib/StyleDictionary.js:235:20) {
@rocket.chat/fuselage-tokens:build:   code: 'ERR_INVALID_ARG_TYPE'
@rocket.chat/fuselage-tokens:build: }
@rocket.chat/fuselage-tokens:build: 
@rocket.chat/fuselage-tokens:build: Node.js v18.20.5
@rocket.chat/fuselage-tokens:build: ERROR: ".:build" exited with 1.
@rocket.chat/fuselage-tokens:build: ERROR: command finished with error: command (/home/dhruv/fuselage/packages/fuselage-tokens) /tmp/xfs-889d5509/yarn run build exited (1)
@rocket.chat/fuselage-tokens#build: command (/home/dhruv/fuselage/packages/fuselage-tokens) /tmp/xfs-889d5509/yarn run build exited (1)

 Tasks:    8 successful, 11 total
Cached:    8 cached, 11 total
  Time:    4.97s 
Failed:    @rocket.chat/fuselage-tokens#build

 ERROR  run failed: command  exited (1)
dhruv@dhruv-Inspiron-13-5320:~/fuselage$ 

The build process fails with the error mentioned above in the @rocket.chat/fuselage-tokens package.

Environment:
Node.js version: v18.20.5
Yarn version: v2.2.3
Operating System: Ubuntu 22.04

Also,
I have confirmed that all dependencies are installed correctly and that no other errors appear before this one. I have also tried clearing the cache and reinstalling, but the issue persists.

Would appreciate any guidance on how to resolve this issue.

![Screenshot from 2024-11-27 21-39-58](https://github.com/user-attachments/assets/86e81a0e-71f1-43c8-a891-98aa2c7d37d3)
![Screenshot from 2024-11-27 21-40-24](https://github.com/user-attachments/assets/27421c08-263f-474c-957f-a1230f54117d)
![Screenshot from 2024-11-27 21-40-38](https://github.com/user-attachments/assets/ab0a4ded-dd98-4551-9cb8-f0dbd145eef1)

**Comment by dougfabris** [comment]
Please, try to delete your `yarn` cache and run `yarn` and `yarn build` again
