### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by umakantv** [RocketChat/fuselage#425]
**Is the team working on any slider component?**

I was expecting a slider in the Forms part in the storybook but couldn't find. Surprisingly, project hasn't needed it till now. 
I require it for this feature:
Pausing notifications for a few minutes. 
I want the user to be able to choose using a slider, although I can use a number input as well for the time being.

**Expected behavior**
* Able to pass min and max value.
* If possible, the component should handle checkpoints/marks/step-size.

**Image**
![image](https://user-images.githubusercontent.com/41837826/113708865-67f70180-96ff-11eb-8481-87fb0d845a26.png)
![image](https://user-images.githubusercontent.com/41837826/113708904-7513f080-96ff-11eb-9b72-a795d7835bb4.png)

**Comment by dougfabris** [comment]
@umakantv We didn't have a case where we needed a more "advanced" range component. For our needs, we use the approach below, maybe it can help you.
```
<Box display='flex'>
    <Box is='input' type='range' value={100} min='0' max='100'/>
  <Tooltip placement='right-top' mis='x8'>{100}</Tooltip>
</Box>;
```
![image](https://user-images.githubusercontent.com/27704687/126717477-82ddd5e7-39af-4bc6-afd1-2aa5ebab9cd1.png)

Thanks for your suggestion!
