### ISSUE TITLE
message-parser:  [LinkName](myurl.org/some space/index.html)

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/fuselage#542]
**Description**
[LinkName](myurl.org/some space/index.html)
`[LinkName](myurl.org/some space/index.html)`

**Steps to reproduce**

**Insert an image/gif**

**Comment by Vansh5632** [comment]
@ggazzo can you just elaborate this issue and i am trying to work on this issue so  that i can work on it in better manner
