### ISSUE TITLE
Docs and types

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/fuselage#63]
provide a good way to document and export component types

**Comment by divyanshuagarwal-23** [comment]
Hey @ggazzo , I'd love to contribute to this project by taking on the documentation work. Can you please assign it to me? I'm eager to get started! 📚

**Comment by dougfabris** [comment]
Hi @divyanshuagarwal-23 , thanks for the contribution! 🚀 💯 

Sorry, this is not an issue anymore. Actually, we use Storybook to automatically document our components. 
Feel free to propose something or help us with another contribution!

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
