### ISSUE TITLE
Icons: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference

### ISSUE THREAD

**Issue by aya986** [RocketChat/fuselage#735]
I would like to use **@rocket.chat/icons** as dependency in my project

but when this npm would build by  tsc command i face with this message

**A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference**

from **@rocket.chat/icons/index.d.ts** 
and from this code 

`declare const Icons= {
  "arrow-back": "\u2989",
  "arrow-collapse": "\ue095",
  ...
  `

How am i able to fix this error?

**Comment by dougfabris** [comment]
@aya986 can you provide more details about how you're building your typescript, your `tsconfig.json` file, or something else that can illustrate better?

**Comment by lent85** [comment]
Same problem

tsconfig.json is default generated from rc-apps command

`{
"compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    },
"include": [
    "**/*.ts"
    ]
}
`

**Comment by myselfmohdsameer** [comment]
I am facing similar issue, I believe it appeared when I upgraded ui-kit in my RC app. @dougfabris @tapiarafael @d-gubert

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

The issue was fixed here: #1123 and it was released on `0.31.25` version!

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
