### ISSUE TITLE
message-parser: trailing punctuation including periods are included in urls/links extracted from messages

### ISSUE THREAD

**Issue by IllTamer** [RocketChat/fuselage#996]
**Description**

- Here is the description of the problem [Origin issue](https://github.com/RocketChat/Rocket.Chat/issues/28314)
- When I started to fix it, I found that there was also a [problem](https://github.com/RocketChat/Rocket.Chat/pull/28340) in the project `message-parser`.

**Steps to reproduce**

As of the `6.0.0-develop` version I tested with, this problem still exists

**Comment by hugocostadev** [comment]
closing in favor of: https://github.com/RocketChat/Rocket.Chat/issues/28314

thanks for contributing, we are following up on that issue
